env:
    # OrangeFox Sync Repository
    FOX_SYNC: https://gitlab.com/OrangeFox/sync.git

    # Device
    FOX_BRANCH: fox_11.0
    DT_LINK: https://github.com/Alone0316/recovery_samsung_a52sxq.git
    DEVICE: a52sxq
    OEM: samsung
    TARGET: recoveryimage

    DT_PATH: device/$OEM/$DEVICE
    OUTPUT: OrangeFox*.zip

    # Extra Command
    EXTRA_CMD: git clone https://github.com/OrangeFoxRecovery/Avatar.git misc

    # Not Recommended to Change
    SYNC_BRANCH: $(echo ${FOX_BRANCH} | cut -d_ -f2)
    SYNC_PATH: $HOME/work # Full (absolute) path. Use "$HOME" instead of "~".
    USE_CCACHE: 1
    CCACHE_SIZE: 50G
    CCACHE_DIR: $HOME/work/.ccache
    J_VAL: 16

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

    # Telegram
    TG_CHAT_ID: ENCRYPTED[-1001283860476]
    TG_TOKEN: ENCRYPTED[2049436092:AAGobgTgnXbNbeYgG7RdiPINcCnDhxbP8XU]

task:
  name: "Recovery Build"
  trigger_type: manual
  timeout_in: 120m
  container:
      image: registry.gitlab.com/sushrut1101/docker:latest
      cpu: 8
      memory: 32G

  Sync_script:
      - bash sync.sh

  Build_script:
      - bash build.sh

  Upload_script:
      - export TIMEOUT=43200 # Link timeout (in minutes)
      - bash upload.sh
