env:
    # OrangeFox Sync Repository
    FOX_SYNC: https://gitlab.com/OrangeFox/sync.git

    # Device
    FOX_BRANCH: 11.0
    DT_LINK: https://github.com/Alone0316/recovery_xiaomi_mido.git
    DEVICE: mido
    OEM: xiaomi
    TARGET: recoveryimage

    DT_PATH: device/$OEM/$DEVICE
    OUTPUT: OrangeFox*.zip

    # Extra Command
    EXTRA_CMD: git clone https://github.com/OrangeFoxRecovery/Avatar.git misc

    # Not Recommended to Change
    SYNC_BRANCH: ${FOX_BRANCH}
    SYNC_PATH: $HOME/work # Full (absolute) path. Use "$HOME" instead of "~".
    USE_CCACHE: 1
    CCACHE_SIZE: 50G
    CCACHE_DIR: $HOME/work/.ccache
    J_VAL: 16

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

    # Telegram
    TG_CHAT_ID: ENCRYPTED[e71e4118b2ec3509700ba9a0b99627f22c7741572d02ee52e507341c4c3c24601bbec75329f67f260b3d98d066a545f9]
    TG_TOKEN: ENCRYPTED[29fedafd88f2250ee816d30f9390c8c4d703c95413f05744f5989da3acf2170b07d8aba426c7b23c04d52ef9f100f1ee]

task:
  name: "Recovery Build"
  timeout_in: 120m
  container:
      image: registry.gitlab.com/sushrut1101/docker:latest
      cpu: 8
      memory: 32G

  Sync_script:
      - bash sync.sh

  Build_script:
      - bash build.sh

  Upload_script:
      - export TIMEOUT=43200 # Link timeout (in minutes)
      - bash upload.sh
